export const GRAPH_DATA = [
  {
    topX: 50,
    topY: 5,
    bottomX: 25,
    bottomY: 30,
    topVertexValue: 1,
    hasTopVertex: true,
    bottomVertexValue: 2,
  },
  {
    topX: 50,
    topY: 5,
    bottomX: 75,
    bottomY: 30,
    bottomVertexValue: 3,
  },
  { topX: 25, topY: 30, bottomX: 15, bottomY: 55, bottomVertexValue: 4 },
  {
    topX: 25,
    topY: 30,
    bottomX: 35,
    bottomY: 55,
    bottomVertexValue: 5,
  },
  {
    topX: 75,
    topY: 30,
    bottomX: 65,
    bottomY: 55,
    bottomVertexValue: 6,
  },
  {
    topX: 75,
    topY: 30,
    bottomX: 85,
    bottomY: 55,
    bottomVertexValue: 7,
  },
  {
    topX: 15,
    topY: 55,
    bottomX: 10,
    bottomY: 80,
    bottomVertexValue: 8,
  },
  {
    topX: 15,
    topY: 55,
    bottomX: 20,
    bottomY: 80,
    bottomVertexValue: 9,
  },
  {
    topX: 35,
    topY: 55,
    bottomX: 30,
    bottomY: 80,
    bottomVertexValue: 10,
  },
  {
    topX: 35,
    topY: 55,
    bottomX: 40,
    bottomY: 80,
    bottomVertexValue: 11,
  },
  {
    topX: 65,
    topY: 55,
    bottomX: 60,
    bottomY: 80,
    bottomVertexValue: 12,
  },
  {
    topX: 65,
    topY: 55,
    bottomX: 70,
    bottomY: 80,
    bottomVertexValue: 13,
  },
  {
    topX: 85,
    topY: 55,
    bottomX: 80,
    bottomY: 80,
    bottomVertexValue: 14,
  },
  {
    topX: 85,
    topY: 55,
    bottomX: 90,
    bottomY: 80,
    bottomVertexValue: 15,
  },
];
